### ISSUE TITLE
MRR problem

### ISSUE THREAD

**Issue by usernameuiui** [ZihaoLi97/WSDM23-DGNNs--for-Session-based-Recommendation#1]
![image](https://user-images.githubusercontent.com/95755511/225893756-bd30a963-ea21-4703-ac51-ded803a01767.png)
![image](https://user-images.githubusercontent.com/95755511/225893810-d90b880f-96fe-4685-abff-a81fccdac0c3.png)
Hello, why am I running your code locally with a MRR that is so much higher than what you wrote in your paper?

**Comment by YuhanZhen** [comment]
Thanks for your problem. As I described in the conclusion section in our paper, the training process may be sort of unstable due to random batch splitting and adaptive graph construction. Consequently, if we change the batch size and random seed, the final results will fluctuate to some extent. I also revise the code and add some supplemented material. Expecting to be helpful.

**Comment by usernameuiui** [comment]
Hello, I would like to ask if the indicator MRR is equivalent to MMR, and the indicator Recall is equivalent to HR?

**Comment by usernameuiui** [comment]
Thanks for your reply. I would like to ask if the indicator MRR is equivalent to MMR, and the indicator Recall is equivalent to HR?

**Comment by YuhanZhen** [comment]
Yes, thanks for your kind reminder, I will correct them in the code.

**Comment by yanghangchen** [comment]
![image](https://user-images.githubusercontent.com/110599467/227145931-1c8a028f-9141-41d0-8b10-f607c609820d.png)
Hello, I would like to ask why the total loss of my training is so large？

**Comment by YuhanZhen** [comment]
Thank you for your kind question. According to my training experience, there are some instances will generate very large losses in the training process, I am also curious about this phenomenon, but please be patient, the model could converge after a few epochs. You may find this phenomenon if you retrain several times. Hopefully, I could answer your question.

**Comment by yanghangchen** [comment]
> 谢谢你的善意提问。根据我的训练经验，有些实例在训练过程中会产生非常大的损失，我对这种现象也很好奇，但请耐心等待，模型在几个时期后可能会收敛。如果您多次重新训练，您可能会发现这种现象。希望我能回答你的问题。

thank you

**Comment by yanghangchen** [comment]
> 谢谢你的善意提问。根据我的训练经验，有些实例在训练过程中会产生非常大的损失，我对这种现象也很好奇，但请耐心等待，模型在几个时期后可能会收敛。如果您多次重新训练，您可能会发现这种现象。希望我能回答你的问题。

Thank you for your reply

**Comment by yanghangchen** [comment]
Hello，I would like to ask whether the  indicator is the best or average？

**Comment by YuhanZhen** [comment]
Not the best, we choose a moderate result to report.

**Comment by yanghangchen** [comment]
> Not the best, we choose a moderate result to report.

Thank you for your reply

**Comment by yanghangchen** [comment]
hello,I would like to ask why the average value of the MRR indicator I run locally is much higher than the data in your paper?
